### ISSUE TITLE
Date ranges on special events

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#164]
When creating special events:

- Timezones seem to be GMT?  Should we have it set to always be local time in LA? Do we need to worry that things will break over a DST change? SCALE is almost always on the weekend where DST kicks in.  Do we need to worry about all session and event times shifting when that happens?

<img width="377" height="56" alt="Image" src="https://github.com/user-attachments/assets/a08b83d6-5397-4fc4-8f51-ba2e4fffa58b" />

- If no date is specified can we just not show a date? Currently will display "No date available"

- When setting dates can we make time optional? We dont always know the times until closer to the show.

- When setting multiple dates it seems to do something goofy.  Eg Here is a event set for March 5  2026 9am - March 6 2026 5pm.

<img width="430" height="273" alt="Image" src="https://github.com/user-attachments/assets/aa1e055b-d9e9-409f-b25c-88c9e54e779b" />

<img width="377" height="56" alt="Image" src="https://github.com/user-attachments/assets/a08b83d6-5397-4fc4-8f51-ba2e4fffa58b" />

Note that while its set to cross 2 dates it shows a start of March 5th 18:00 (see previous note about timezones)  and an end of 1am without a date.

**Comment by irabinovitch** [comment]
@DrupalPhil Thanks for looking at this. It seems like we're still not showing date ranges though, only the first day

**Comment by DrupalPhil** [comment]
> If no date is specified can we just not show a date? Currently will display "No date available"

I'm not seeing this. Can you share where you're seeing this?

> When setting dates can we make time optional? We dont always know the times until closer to the show.

I'll need to look into this another time

> When setting multiple dates it seems to do something goofy. Eg Here is a event set for March 5 2026 9am - March 6 2026 5pm.

Fixed.

**Comment by DrupalPhil** [comment]
Checking is on this one.

**Comment by irabinovitch** [comment]
@DrupalPhil 
The no dat range available issue is still present.  I removed the dates on Astricon and got this. I'm going to add them back now.

<img width="436" height="184" alt="Image" src="https://github.com/user-attachments/assets/874ab953-775f-498b-af9f-fd4278bcd6c3" />

**Comment by irabinovitch** [comment]
The missing end date issue was fixed in #247
