### ISSUE TITLE
Address past and future spam

### ISSUE THREAD

**Issue by DrupalPhil** [socallinuxexpo/scale-drupal#212]
1. Remove spam users / content
2. Add spam prevention

**Comment by DrupalPhil** [comment]
Any thoughts on a formula I can use to programmatically remove spam users?

For instance (all criteria must be satisfied):

1. User has NEVER logged in
2. Email contains one of the following strings: ['termites', 'another', 'somethingelse']
3. User not associated with a "Speaker" entity
4. ?? Thoughts?

Also, is there any spam _content_ that should be removed? 

@kcbraunschweig @irabinovitch

**Comment by irabinovitch** [comment]
anything mentioning termites can probably go 😂

**Comment by irabinovitch** [comment]
i say that because there are 150~ accounts with termites in the user or domain.

**Comment by DrupalPhil** [comment]
One of the only _bugs_ that actually spans our realities.

**Comment by DrupalPhil** [comment]
I've deployed a honeypot to the user registration form.

**Comment by kcbraunschweig** [comment]
Any ideas how we can get some metrics around this? Trying to figure out how to tell if the honeypot made a difference. 
Have we done the data cleanup?

**Comment by irabinovitch** [comment]
I can confirm we still get daily spam sign ups. I dont know if its more or less than before. I dont recall if we did clean up, but we definitely need to do it for the new spam regardless..
